### ISSUE TITLE
BoundsError: attempt to access 1-element Array{BGZFStreams.Block,1} at index [2]

### ISSUE THREAD

**Issue by CiaranOMara** [BioJulia/BGZFStreams.jl#22]
Encountered in https://github.com/BioJulia/XAM.jl/issues/31
 and reproduced by [line 286](https://github.com/BioJulia/XAM.jl/blob/70a4e94e5ce13ecc77595a73c83c61f7d702c660/test/test_bam.jl#L286-L286) in https://github.com/BioJulia/XAM.jl/tree/hotfix/issue-31.

It appears there is a case where `ensure_buffered_data` increments the `stream.block_index` past the end of the `stream.blocks` array. I haven't had the time to understand how this might occur.
https://github.com/BioJulia/BGZFStreams.jl/blob/37f33e0416ce7c76768854602a2e7e7fecbd4781/src/bgzfstream.jl#L315-L330

**Comment by lysogeny** [comment]
I think this is a problem introduced in 1a54e350fefca90eaf4c49a8e142ede7be219d5a. 

To explain what I think is happening in this problem:

- The loop iterates through each of the blocks (one per thread) and checks if the block isn't at the last byte (i.e. there is remaining data). It increments the index and tries again. Once a block with remaining bytes is found, it returns that block's index.
- If there are no blocks with remaining bytes, the loop breaks. Should there still be file left, new blocks are read and the `@goto` jumps the flow back to the beginning of the function.
- Should this happen, the `stream.block_index` is however never returned to a smaller value (it still is at `lastindex(stream.blocks)`) and in the next increment can exceed the `Vector`'s bound.

To me it looks like this is a way of going to the next set of blocks if the current ones have been read. As such, I think the correct way of dealing with this should be to reset `stream.block_index` to 1 in `if !eof(stream.io)`.

I will try this to see if that fixes the issue for me. 
In the meanwhile, perhaps @bicycle1885 has some thoughts on this? I still don't understand how the too-high value is actually returned as the while loop should not be run if the `block_index` is too high and the only other return returns 0.

**Comment by lysogeny** [comment]
Actually, disregard what I said, `read_blocks!` [sets](https://github.com/BioJulia/BGZFStreams.jl/blob/37f33e0416ce7c76768854602a2e7e7fecbd4781/src/bgzfstream.jl#L395) `stream.block_index = 1`

**Comment by lysogeny** [comment]
Okay, I think I got it this time:

- `stream.block_index` gets incremented to one larger than the maximum because no block has data remaining.
- if we are now `eof`, `ensure_buffered_data` returns `0`.
- the problem then lies [here](https://github.com/BioJulia/BGZFStreams.jl/blob/37f33e0416ce7c76768854602a2e7e7fecbd4781/src/bgzfstream.jl#L155). should `ensure_buffered_data` return `0`, `stream.block_index` (previously set to larger than maximum) gets used instead of the index, thus causing a `BoundsError`

Should this thus be fixed by ensuring that if `0` is returned, stream.block_index is set to a valid value, or should this be fixed by handling the `0` properly?
My understanding of this is that if a `0` is returned, the IO stream is `eof`. This means that the currently inflated blocks are the last blocks, and we probably need to use the last block to calculate the `virtualoffset`. The solution must thus be to change [line 156](https://github.com/BioJulia/BGZFStreams.jl/blob/37f33e0416ce7c76768854602a2e7e7fecbd4781/src/bgzfstream.jl#L156) from
```
block = stream.blocks[stream.block_index]
```
to
```
block = stream.blocks[end]
```

A possibly concerning consequence of this:

- `ensure_buffered_data` and thus `virtualoffset` both actually mutate the `stream` object. Shouldn't these functions by convention be called `ensure_buffered_data!` and `virtualoffset!`? Is it even safe to use these functions?

**Comment by lysogeny** [comment]
I have no idea if there is any active maintainers on this project at the moment. I have forked this and fixed the issue as described in the above problem here: https://github.com/lysogeny/BGZFStreams.jl

If anyone is experiencing this problem I would be interested if using that version fixes it.

**Comment by kescobo** [comment]
Apologies for the lack of response - I think the primary author of this package is not nearly as involved in open source of late. If you want to open a PR with your fix, I'm happy to take a look (though I'm afraid I'm not capable of providing a substantive review).

**Comment by CiaranOMara** [comment]
I'm closing this issues as I think the solution should be implemented in XAM with the addition of either a `bytesavailable` or `eof` check. I haven't had time to determine which check is the better/more appropriate approach.


**Notes:**
On approach uses BGZFStreams's [`eof`](https://github.com/BioJulia/BGZFStreams.jl/blob/37f33e0416ce7c76768854602a2e7e7fecbd4781/src/bgzfstream.jl#L204-L210).
https://github.com/BioJulia/XAM.jl/blob/bc4e8267f7de71ec4f788513ab5c58ab101f7f8e/src/bam/overlap.jl#L66

The other uses TranscodingStreams's, [`bytesavailable`](https://github.com/JuliaIO/TranscodingStreams.jl/blob/e4b7e0f1823826ccf58182d54155ef4257b9f6ad/src/stream.jl#L384-L387), which in turn uses [`buffersize`](https://github.com/JuliaIO/TranscodingStreams.jl/blob/e4b7e0f1823826ccf58182d54155ef4257b9f6ad/src/buffer.jl#L50-L52).
https://github.com/BioJulia/XAM.jl/blob/5fb6af732b7885aa7f3db6bec817a6b16f1ac645/src/bam/overlap.jl#L66

The `bytesavailable` approach was inspired by the code lifted into Indexes.jl.
https://github.com/BioJulia/Indexes.jl/blob/e417c6851314c410d5afb15ff44d36752587d70f/src/overlap.jl#L50

**Comment by lysogeny** [comment]
I don't think this should be fixed in `XAM.jl`, as that would effectively leave `BGZFStreams.jl` broken. People interested in dealing with `BGZFStreams` directly would then have a broken implementation (such as myself).

I actually forgot to mention this, but the reason I even found this issue was that I was using `virtualoffset`, and not using `eachoverlap` in XAM (although that is the first time I encountered this issue).

**Comment by CiaranOMara** [comment]
In the case of XAM, a `VirtualOffset` beyond the bounds of the BGZFStream is requested. That is there are no more `BGZFStream.blocks` to load and `block.position` in the last `BGZFStream.blocks` is greater than `block.size`.

So maybe an "out of bounds" error is appropriate? Or maybe it is acceptable to calculate an offset that is beyond the bounds of the stream? I prefer the latter approach as it may allow `Indexes.chunk.stop` at 
https://github.com/BioJulia/XAM.jl/blob/0e6ef62e3e881d5e1b32441bb820dce1e9c5ed72/src/bam/overlap.jl#L65 to work as intended, and XAM wouldn't need to take a performance hit with the inclusion of an additional `eof` check.

I think the if zero case here would be as follows:
```julia
if i == 0
    # Provide a VirtualOffset beyond the bounds of the stream.
    block = stream.blocks[end]
    return VirtualOffset(block.block_offset + block.size, block.position - block.size - 1)
else
```

**Comment by CiaranOMara** [comment]
I had another look at the if zero case. The return in @lysogeny's PR is equivalent to what I've suggested above. Their PR #25 has my support.
